#!/bin/bash
# Quick setup guide for testing

echo "========================================="
echo "🚀 AI Operations Assistant - Quick Setup"
echo "========================================="
echo ""
echo "Your .env file needs real API keys."
echo ""
echo "1️⃣  OpenAI API Key"
echo "   Go to: https://platform.openai.com/api-keys"
echo "   Copy your API key"
echo ""
echo "2️⃣  GitHub Personal Access Token"
echo "   Go to: https://github.com/settings/tokens"
echo "   Generate new token with 'public_repo' permission"
echo ""
echo "3️⃣  OpenWeather API Key"
echo "   Go to: https://openweathermap.org/api"
echo "   Sign up (free tier works)"
echo ""
echo "4️⃣  Edit .env file"
echo "   nano .env"
echo "   Or open in VS Code"
echo ""
echo "5️⃣  Replace placeholder values with your actual keys:"
echo "   OPENAI_API_KEY=sk-your-actual-key"
echo "   GITHUB_TOKEN=ghp_your-actual-token"
echo "   OPENWEATHER_API_KEY=your-actual-key"
echo ""
echo "6️⃣  Save and restart server"
echo "   uvicorn main:app --reload"
echo ""
echo "========================================="
